### ISSUE TITLE
Doesnt work with heaps because of haxe 4.0

### ISSUE THREAD

**Issue by tobias1012** [colyseus/colyseus-hx#6]

**Comment by endel** [comment]
hey @tobias1012, I haven't tested this library against haxe 4.0, it's still in preview right?

do you have compilation errors?

**Comment by tobias1012** [comment]
Yes, I have to run Hashlink but i found an old version, the haxe documentation was a bit vague
